language: java
jdk:
- oraclejdk8
# would just use default install/script but the ./mvnw script errors on travis
# obviously this only works for maven builds right now...
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn test
deploy:
  provider: heroku
  api_key:
    secure: 1064d52f-7372-481f-88d0-3eb6ceedfd23
  app: currency-converter-app
