language: java
jdk:
- openjdk8
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn package
- 
deploy:
  provider: cloudfoundry
  username: rinivermais158@gmail.com
  password: sA9@verma
  api: https://api.run.pivotal.io
  organization: currency-converter-app
  space: development
  buildpack: https://github.com/cloudfoundry/java-buildpack
