language: java
jdk:
- openjdk8
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn package
deploy:
  provider: cloudfoundry
  username: rinivermais158@gmail.com
  password: 
    secure: hoVfgAnB7r46opBrSn+Zm+J6793/KK1HIDvoah4hI+5IDE8iqD9Rmxkh2RFzaSAokTxztcUjKL6WAT3MaV7AEgMdqGFKpY18f0gJnEoK2EJmb2qxaZAOGYJDtvialHPITJ69/fQ0HGQGFzrMs/YbiFSenZPfaZWcLc1rSzHJ/e3kHbpqFhcQRufKpk8vruVlVg1OJLGXrqOj8ACyaaS0Ux616DwnFHjhtGd3HXJMh+aqsGyXJp26sr9eN5NadFzHYWu4vhNEGVvdOywZ2fY/fniiWUo2zPeJqkKcRQEzXEGQJ1eu0C7ApElUqlVJgirSnD0gzX/kCCZONjoDURRcNj2QJelq62oI0NIfuJLdnsoVYo43jUH59gAQHbjEV/Oc7tK5hVYo1Ddi5q8VPTlNAkQciPqeyXOS1s57bhZzhGH7RauowitpqK1XnjODqS94ehjfvYCZYgTcAUwWqiNBrVWRVDIMdCkkrOW4eA2fL+LWZZBd1VymC50XLoP9NCyhwwne74BXKwYfETYg+OMYmsmgTwCMTuiitgg7+ce3Fj96dXoJoHc4ddcaQC7K69O3xFnO6ZF8LI6IpmGK/eX33WNuU768wROweAdKX7AfycWC2T1/ixC4AzCvMnXtppTdlN6wLjZyf/5LAxlCt10v3rNDhm2lJJIjaKVtZPQQ=
  api: https://api.run.pivotal.io
  organization: currency-converter-app
  space: development
  buildpack: https://github.com/cloudfoundry/java-buildpack
